name: chat_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  chat_app_ui:
    path: packages/chat_app_ui
  chat_repository:
    path: packages/chat_repository
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^13.2.1
  image_picker: ^1.0.4
  intl: ^0.18.0
  media_picker:
    path: ./packages/media_picker
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  uuid: ^4.2.1

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
